### ISSUE TITLE
App seen as a virus on my system, wont let me download

### ISSUE THREAD

**Issue by tonycaidotcom** [rafallz10100/IntunewinBuilder#1]
App seen as a virus on my system, wont let me download - need to sign it or something.

**Comment by rafallz10100** [comment]
The installer and the exe file are signed with my certificate:
![image](https://github.com/rafallz10100/IntunewinBuilder/assets/151853443/6150f19b-58fd-455e-93fb-df3f40ec471e)
![image](https://github.com/rafallz10100/IntunewinBuilder/assets/151853443/ece8ca47-cf02-4f32-80ca-dca771c9a2c6)

I assume this is about:
![image](https://github.com/rafallz10100/IntunewinBuilder/assets/151853443/046f9cdd-06ef-482d-9163-de94137b6530)

You can bypass this by selecting the 3 dots and selecting keep.
![image](https://github.com/rafallz10100/IntunewinBuilder/assets/151853443/a2742f6e-ca60-4cfd-9449-357937a1f4b2)

This application is simply not trusted by Defender Smart Screen. As the owner of the application, I have no influence on whether it is trusted by Smart Screen.

I sent a request on the website informing that the attachment is trusted https://feedback.smartscreen.microsoft.com/feedback.aspx
Maybe this will help
